/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moto;

import java.awt.Color;
import java.awt.List;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author admin
 */
public class Memory extends javax.swing.JFrame {

    
     public ArrayList<String> GH=new ArrayList<>();
    public  DefaultListModel list=new DefaultListModel();
      public ArrayList<VALEUR> G=new ArrayList<>();
   
    /**
     * Creates new form Memory
     */
  int RUNNING=0;
   
  
public Memory()
{
    initComponents();
     SETICOn();
     LIST.setModel(list);
         String B="0000   00,0001   00,0002   00,0003   00,0004   00,0005   00,0006   00,0007   00,0008   00,0009   00,000A   00,000B   00,000C   00,000D   00,000E   00,000F   00,0010   00,0020   00,0030   00";
         
         String T[]=B.split(",");
                       setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

         for(String h:T)
         {
             GH.add(h);
         }      
         for(int i=0;i<GH.size();i++)
             list.addElement(GH.get(i));
         
}
 static  String  STFX;
public Memory(String STFX)
{
   this.STFX=STFX;
        
         // list.setElementAt(GH.set(VALEUR.I, STFX), VALEUR.I);
          
}
public void MEMSET(String STR,String VAL)
{
    int index=0;

    for(String VAR :GH)
    {
        
       String B[]=VAR.split("   ");
      
       
       if(B[0].equalsIgnoreCase(STR))
           break;
          
          index++;  
    }
    String K=GH.get(index);
    String H[]=K.split("   ");
    K=H[0]+"   "+VAL;
    GH.set(index, K);
    list.setElementAt(GH.get(index), index);
    
    
}
public String  MEMGET(String STR)
{
    String VAL;
    int index=0;

    for(String VAR :GH)
    {
        
       String B[]=VAR.split("   ");
      
       
       if(B[0].equalsIgnoreCase(STR))
           break;
          
          index++;  
    }

  
  String LP =list.getElementAt(index).toString();
  String NVAL[]= LP.split("   ");
  VAL=NVAL[1];
  return VAL;
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        LIST = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        PA1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(180, 218));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LIST.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "0000   00", "0001   00", "0002   00", "0003   00", "0004   00", "0005   00", "0006   00", "0007   00", "0008   00", "0009   00", "000A   00", "000B   00", "000C   00", "000D   00", "000E   00", "000F   00", "0010   00", "0020   00", "0030   00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LIST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LISTMouseClicked(evt);
            }
        });
        LIST.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                LISTInputMethodTextChanged(evt);
            }
        });
        LIST.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LISTKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LISTKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(LIST);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 188));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 0, 19, -1));

        PA1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RAM");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout PA1Layout = new javax.swing.GroupLayout(PA1);
        PA1.setLayout(PA1Layout);
        PA1Layout.setHorizontalGroup(
            PA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PA1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        PA1Layout.setVerticalGroup(
            PA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int j=0;
public void RESET()
{
     String B="0000   00,0001   00,0002   00,0003   00,0004   00,0005   00,0006   00,0007   00,0008   00,0009   00,000A   00,000B   00,000C   00,000D   00,000E   00,000F   00,0010   00,0020   00,0030   00";
         
         String T[]=B.split(",");
          for(int i=0;i<T.length;i++)
      {
          GH.set(i, T[i]);
      }  
         for(int i=0;i<GH.size();i++)
             list.setElementAt(GH.get(i),i);
         
}
public void ACT(int I,String VAL)
{
    String STR=list.getElementAt(I).toString();
    String B[]=STR.split("   ");
    B[1]=VAL;
    STR=B[0]+"   "+B[1];
  
   list.setElementAt(GH.set(I, STR),I);
   
   
}
public void setST(String STFX)
{
    this.STFX=STFX;
}


    private void LISTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LISTMouseClicked
       if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
       {
        
        int i=LIST.getSelectedIndex();
     
      
      if(i!=-1)
      {
          
          VALEUR  b=new VALEUR(LIST.getSelectedValue().toString(),i);
         
        
         
          if(j>0)
        G.get(j-1).dispose();
              
G.add(b);
            b.setVisible(true);
            
          
          b.setLocationRelativeTo(null);
        
          j++;
          
       

      }
       }
       
    }//GEN-LAST:event_LISTMouseClicked

    private void LISTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_LISTInputMethodTextChanged
System.out.println("GAHDG");
    }//GEN-LAST:event_LISTInputMethodTextChanged

    private void LISTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LISTKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_LISTKeyTyped

    private void LISTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LISTKeyPressed
if(evt.getKeyChar()== KeyEvent.VK_ENTER)
{
list.setElementAt(GH.set(VALEUR.I, STFX),VALEUR.I);

}
       
    }//GEN-LAST:event_LISTKeyPressed
 private void SETICOn() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ICONS//MOTO.png")));
    }
    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new Memory().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LIST;
    private javax.swing.JPanel PA1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
