/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moto;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author admin
 */
public class MOTO_INTERFACE extends javax.swing.JFrame {

    /**
     * Creates new form MOTO_INTERFACE
     */
    
    public MOTO_INTERFACE() {
        initComponents();
        SETICOn();
         Border NAM=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
         IMAGE1.setBorder(NAM);
         CHECK.setVisible(false);
         
       
       //  HINZS.setBorder(NAM);
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        IMAGE1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Y = new javax.swing.JTextField();
        MES = new javax.swing.JTextField();
        DP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        U = new javax.swing.JTextField();
        BT = new javax.swing.JTextField();
        PC = new javax.swing.JTextField();
        EFH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        S = new javax.swing.JTextField();
        X = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CHECK = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(461, 385));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IMAGE1.setBackground(new java.awt.Color(198, 198, 198));
        IMAGE1.setMaximumSize(new java.awt.Dimension(470, 410));
        IMAGE1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moto/ICONS/Screenshot 2023-11-25 031437.png"))); // NOI18N
        IMAGE1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 150));

        Y.setBackground(new java.awt.Color(198, 198, 198));
        Y.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Y.setForeground(new java.awt.Color(0, 0, 255));
        Y.setText("0000");
        Y.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YMouseClicked(evt);
            }
        });
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        Y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                YKeyTyped(evt);
            }
        });
        IMAGE1.add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 70, 30));

        MES.setBackground(new java.awt.Color(198, 198, 198));
        MES.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MES.setForeground(new java.awt.Color(0, 0, 255));
        MES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        MES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MESActionPerformed(evt);
            }
        });
        MES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MESKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MESKeyTyped(evt);
            }
        });
        IMAGE1.add(MES, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 200, 30));

        DP.setBackground(new java.awt.Color(198, 198, 198));
        DP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DP.setForeground(new java.awt.Color(0, 0, 255));
        DP.setText("00");
        DP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        DP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPActionPerformed(evt);
            }
        });
        DP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DPKeyTyped(evt);
            }
        });
        IMAGE1.add(DP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 50, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S");
        IMAGE1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 60, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PC");
        IMAGE1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 60, 40));

        U.setBackground(new java.awt.Color(198, 198, 198));
        U.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        U.setForeground(new java.awt.Color(0, 0, 255));
        U.setText("0000");
        U.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UMouseClicked(evt);
            }
        });
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        U.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UKeyTyped(evt);
            }
        });
        IMAGE1.add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 60, 30));

        BT.setBackground(new java.awt.Color(198, 198, 198));
        BT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BT.setForeground(new java.awt.Color(0, 0, 204));
        BT.setText("00");
        BT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTMouseClicked(evt);
            }
        });
        BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActionPerformed(evt);
            }
        });
        BT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BTKeyTyped(evt);
            }
        });
        IMAGE1.add(BT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 265, 50, 30));

        PC.setBackground(new java.awt.Color(198, 198, 198));
        PC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PC.setForeground(new java.awt.Color(0, 0, 255));
        PC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PC.setText("FC00");
        PC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCActionPerformed(evt);
            }
        });
        PC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PCKeyTyped(evt);
            }
        });
        IMAGE1.add(PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 100, 30));

        EFH.setBackground(new java.awt.Color(198, 198, 198));
        EFH.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EFH.setForeground(new java.awt.Color(0, 0, 255));
        EFH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EFH.setText("00000100");
        EFH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        EFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EFHActionPerformed(evt);
            }
        });
        EFH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EFHKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EFHKeyTyped(evt);
            }
        });
        IMAGE1.add(EFH, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Y");
        IMAGE1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 60, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("U");
        IMAGE1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 60, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("B");
        IMAGE1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 60, 20));

        A.setBackground(new java.awt.Color(198, 198, 198));
        A.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A.setForeground(new java.awt.Color(0, 0, 204));
        A.setText("00");
        A.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
        });
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AKeyTyped(evt);
            }
        });
        IMAGE1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 50, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("A");
        IMAGE1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 185, 60, 20));

        S.setBackground(new java.awt.Color(198, 198, 198));
        S.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        S.setForeground(new java.awt.Color(0, 0, 255));
        S.setText("0000");
        S.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SMouseClicked(evt);
            }
        });
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SKeyTyped(evt);
            }
        });
        IMAGE1.add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 130, 70, 30));

        X.setBackground(new java.awt.Color(198, 198, 198));
        X.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        X.setForeground(new java.awt.Color(0, 0, 255));
        X.setText("0000");
        X.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        X.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                XKeyTyped(evt);
            }
        });
        IMAGE1.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 70, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("E F H I N Z V C");
        IMAGE1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 100, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        IMAGE1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 60, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DP");
        IMAGE1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 60, 20));

        CHECK.setBackground(new java.awt.Color(51, 0, 0));
        CHECK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moto/ICONS/custom113_60.png"))); // NOI18N
        CHECK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CHECKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CHECKMouseExited(evt);
            }
        });
        CHECK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKActionPerformed(evt);
            }
        });
        IMAGE1.add(CHECK, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 40, 30));

        getContentPane().add(IMAGE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YActionPerformed

    private void MESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MESActionPerformed

    private void DPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DPActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UActionPerformed

    private void BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTActionPerformed

    private void PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCActionPerformed

    private void EFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EFHActionPerformed
       
    }//GEN-LAST:event_EFHActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
    
              
              
              
              
              
              
    }//GEN-LAST:event_SActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XActionPerformed
int C=4,v=4;
    private void EFHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EFHKeyTyped
      
       
        
            evt.consume();
        
    }//GEN-LAST:event_EFHKeyTyped
int k=0;
    private void PCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PCKeyTyped
   
        evt.consume();
    }//GEN-LAST:event_PCKeyTyped

    private void MESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MESKeyTyped
      evt.consume();
    }//GEN-LAST:event_MESKeyTyped
java.awt.event.KeyEvent B;
    private void UKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UKeyTyped
       
        
        
        if(evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)
        {
            if(C>0)
          C--;
          
        }
        else
        {
       
        if( C>=4)
        {
            evt.consume();
           
        }
        if(C<4)
         C++;
        }
       
    }//GEN-LAST:event_UKeyTyped
int o=2,n=2,m=4;
    private void UMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UMouseClicked
   
     
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
      {
                C=0;   CHECK.setVisible(true);

      }
           
      
          
    }//GEN-LAST:event_UMouseClicked

    private void SKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SKeyTyped
 if(evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)
        {
            if(v>0)
          v--;
          
        }
        else
        {
       
        if( v>=4)
        {
            evt.consume();
           
        }
        if(v<4)
         v++;
        }


    }//GEN-LAST:event_SKeyTyped

    private void SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseClicked

 if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
 {
         CHECK.setVisible(true);
                v=0;
      }
    }//GEN-LAST:event_SMouseClicked

    private void AKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyTyped
if(evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)
        {
            if(o>0)
          o--;
          
        }
        else
        {
       
        if( o>=2)
        {
            evt.consume();
           
        }
        if(o<2)
         o++;
        }


      

    }//GEN-LAST:event_AKeyTyped

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
{o=0;  
CHECK.setVisible(true);

}
    }//GEN-LAST:event_AMouseClicked

    private void BTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTKeyTyped

if(evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)
        {
            if(n>0)
          n--;
          
        }
        else
        {
       
        if( n>=2)
        {
            evt.consume();
           
        }
        if(n<2)
         n++;
        }
    }//GEN-LAST:event_BTKeyTyped

    private void BTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTMouseClicked

if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
{n=0; 
CHECK.setVisible(true);

}

    }//GEN-LAST:event_BTMouseClicked

    private void XKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_XKeyTyped

if(evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)
        {
            if(m>0)
          m--;
          
        }
        else
        {
       
        if( m>=4)
        {
            evt.consume();
           
        }
        if(m<4)
         m++;
        }

    }//GEN-LAST:event_XKeyTyped
int z=4;

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked

if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
{m=0;    
CHECK.setVisible(true);

}

    }//GEN-LAST:event_XMouseClicked

    private void YKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YKeyTyped
     
        
        if(evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)
        {
            if(z>0)
          z--;
          
        }
        else
        {
       
        if( z>=4)
        {
            evt.consume();
           
        }
        if(z<4)
         z++;
        }
    }//GEN-LAST:event_YKeyTyped

    private void YMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YMouseClicked
       if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
{z=0;
CHECK.setVisible(true);
}
        
    }//GEN-LAST:event_YMouseClicked
public String getA()
{
    return A.getText();
}
public String getB()
{
    return BT.getText();
}
public String gety()
{
    return Y.getText();
}
public String getx()
{
    return X.getText();
}
public String gets()
{
    return S.getText();
}
public String getPC()
{
    return PC.getText();
}
public String getu()
{
    return U.getText();
}
public String getDP()
{
    return DP.getText();
}
public String getMES()
{
    return MES.getText();
}
public void setA(String B)
{
    A.setText(B);
}
public void setB(String B)
{
    BT.setText(B);
}
public void sety(String B)
{
    Y.setText(B);
}
public void setx(String B)
{
    X.setText(B);
}
public void sets(String B)
{
    S.setText(B);
}
public void setPC(String B)
{
    PC.setText(B);
}
public void setU(String B)
{
    U.setText(B);
}
public void setDP(String B)
{
    DP.setText(B);
}
public void setMES(String B)
{
    MES.setText(B);
}

    private void DPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DPKeyTyped
     evt.consume();
    }//GEN-LAST:event_DPKeyTyped
private void jaction(java.awt.event.MouseEvent evt)
{
    A.selectAll();
    
}
public void TERMIN(String INTRU)
{
    MES.setText(INTRU);
}
public void SETPCS(String ID)
{
    PC.setText(ID);
}
public void SETA(String ID)
{
    A.setText(ID);
}
public void SETB(String ID)
{
    BT.setText(ID);
}
public void SETX(String ID)
{
    X.setText(ID);
}
public void SETY(String ID)
{
   Y.setText(ID);
}
public void SETU(String ID)
{
    U.setText(ID);
}
public void SETS(String ID)
{
    S.setText(ID);
}





public String GETPCS()
{
   return PC.getText();
}
public String GETA()
{
    return A.getText();
}
public String GETB()
{
    return BT.getText();
}
public String GETX()
{
    return X.getText();
}
public String GETY()
{
   return Y.getText();
}
public String GETU()
{
    return U.getText();
}
public String GETS()
{
    return S.getText();
}
public void REINS()
{
    PC.setText("FC00");
S.setText("0000");
U.setText("0000");
A.setText("00");
BT.setText("00");
DP.setText("00");
EFH.setText("00000100");
X.setText("0000");
Y.setText("0000");
MES.setText("");

}
    private void CHECKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKActionPerformed

PC.setText(PC.getText());
S.setText(S.getText());
U.setText(U.getText());
A.setText(A.getText());
BT.setText(BT.getText());
DP.setText(DP.getText());
EFH.setText(EFH.getText());
X.setText(X.getText());
Y.setText(Y.getText());
A.requestFocus();
A.selectAll();
CHECK.setVisible(false);

    }//GEN-LAST:event_CHECKActionPerformed

    private void PCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PCKeyPressed
     evt.consume();
    }//GEN-LAST:event_PCKeyPressed

    private void DPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DPKeyPressed
       evt.consume();
    }//GEN-LAST:event_DPKeyPressed

    private void MESKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MESKeyPressed
      evt.consume();
    }//GEN-LAST:event_MESKeyPressed

    private void EFHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EFHKeyPressed
      evt.consume();
    }//GEN-LAST:event_EFHKeyPressed

    private void CHECKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKMouseEntered

BAR.PUT();
        
        
    }//GEN-LAST:event_CHECKMouseEntered

    private void CHECKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKMouseExited
     
        
        BAR.CLEAR();
    }//GEN-LAST:event_CHECKMouseExited

    
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MOTO_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MOTO_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MOTO_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MOTO_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MOTO_INTERFACE().setVisible(true);
            }
        });
    }
 private void SETICOn() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ICONS//MOTO.png")));
    }     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField BT;
    private javax.swing.JButton CHECK;
    private javax.swing.JTextField DP;
    private javax.swing.JTextField EFH;
    private javax.swing.JPanel IMAGE1;
    private javax.swing.JTextField MES;
    private javax.swing.JTextField PC;
    private javax.swing.JTextField S;
    private javax.swing.JTextField U;
    private javax.swing.JTextField X;
    private javax.swing.JTextField Y;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
