/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moto;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.awt.List;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import static moto.Memory.STFX;
/**
 *
 * @author admin
 */
public class ROM extends javax.swing.JFrame {
  public static ArrayList<String> N=new ArrayList<>();
    public static DefaultListModel list=new DefaultListModel();
    /**
     * Creates new form ROM
     */
      public  int I=0;
    public ROM() {
        initComponents();
         SETICOn();
      LIST.setModel(list);
       setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
      String B="FC00    FF,FC01    FF,FC02    FF,FC03    FF,FC04    FF,FC05    FF,FC06    FF,FC07    FF,FC08    FF,FC09    FF,FC0A    FF,FC0B    FF,FC0C    FF,FC0D    FF,FC0E    FF,FC0F    FF,FC10    FF,FC11    FF,FC12    FF,FC13    FF,FC14    FF,FC15    FF,FC16    FF,FC17    FF,FC18    FF,FC19    FF,FC1A    FF,FC1B    FF,FC1C    FF,FC1D    FF,FC1E    FF,FC1F    FF,FC20    FF,FC21    FF,FC22    FF,FC23    FF,FC24    FF,FC25    FF,FC26    FF,FC27    FF,FC28    FF";
      String T[]=B.split(",");
      for(String h :T)
      {
          N.add(h);
      }
      for(String l :N)
      {
          list.addElement(l);
      }
   
    }
    public String ADD(int i)
    {
        return list.getElementAt(i).toString();
        
    }
    public String CHECK;
    public void SETL(String CHECK)
    {
        this.CHECK=CHECK;
        I++;
    }
public void RESETRO()
{
     String B="FC00    FF,FC01    FF,FC02    FF,FC03    FF,FC04    FF,FC05    FF,FC06    FF,FC07    FF,FC08    FF,FC09    FF,FC0A    FF,FC0B    FF,FC0C    FF,FC0D    FF,FC0E    FF,FC0F    FF,FC10    FF,FC11    FF,FC12    FF,FC13    FF,FC14    FF,FC15    FF,FC16    FF,FC17    FF,FC18    FF,FC19    FF,FC1A    FF,FC1B    FF,FC1C    FF,FC1D    FF,FC1E    FF,FC1F    FF,FC20    FF,FC21    FF,FC22    FF,FC23    FF,FC24    FF,FC25    FF,FC26    FF,FC27    FF,FC28    FF";
      String T[]=B.split(",");
      for(int i=0;i<T.length;i++)
      {
          N.set(i, T[i]);
      }
      for(int i=0;i<N.size();i++)
      {
          
          list.setElementAt(N.get(i), i);
      }
}
    public ROM(String CHECK)
    {
      
       
    N.set(INSTRUCTION.BRA, CHECK);
     list.setElementAt(N.get(INSTRUCTION.BRA), INSTRUCTION.BRA);
      
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LIST = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LIST.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "FC00    FF", "FC01    FF", "FC02    FF", "FC03    FF", "FC04    FF", "FC05    FF", "FC06    FF", "FC07    FF", "FC08    FF", "FC09    FF", "FC0A    FF", "FC0B    FF", "FC0C    FF", "FC0D    FF", "FC0E    FF", "FC0F    FF", "FC10    FF", "FC11    FF", "FC12    FF", "FC13    FF", "FC14    FF", "FC15    FF", "FC16    FF", "FC17    FF", "FC18    FF", "FC19    FF", "FC1A    FF", "FC1B    FF", "FC1C    FF", "FC1D    FF", "FC1E    FF", "FC1F    FF", "FC20    FF", "FC21    FF", "FC22    FF", "FC23    FF", "FC24    FF", "FC25    FF", "FC26    FF", "FC27    FF", "FC28    FF" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LIST.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LISTKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(LIST);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROM");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LISTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LISTKeyPressed
       if(evt.getKeyChar()== KeyEvent.VK_ENTER)
{
    

     N.set(INSTRUCTION.BRA, CHECK);
     list.setElementAt(N, INSTRUCTION.BRA);

}
   
    }//GEN-LAST:event_LISTKeyPressed
 private void SETICOn() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ICONS//MOTO.png")));
    }     
    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JList<String> LIST;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
