/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moto;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author admin
 */

public class VALEUR extends javax.swing.JFrame {
Robot robo ;
     /* Creates new form VALEUR
     */
     private  String STF;
   
    public VALEUR(String STR,int I) {
    try {
        robo=new Robot();
    } catch (AWTException ex) {
        Logger.getLogger(VALEUR.class.getName()).log(Level.SEVERE, null, ex);
    }
       this.STR=STR;
       this.I=I;
        initComponents();
         SETICOn();
       setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        String ST[]=STR.split("   ");
        TER.setText("Adresse $"+ST[0]);
        TEX.setText(ST[1]);
       
       
        
       
        
    }
   public VALEUR() {      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   public static String STR;
  
public void setST(String STR)
{
    this.STR=STR;
}
public String getST()
{
    return STR;
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OK = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TER = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TEX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DAKH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        OK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OKKeyTyped(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, 20));

        EXIT.setText("ANNULER");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 90, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TER.setBackground(new java.awt.Color(255, 255, 255));
        TER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TER.setText("Adresse $");
        TER.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setMaximumSize(new java.awt.Dimension(156, 74));
        jPanel2.setMinimumSize(new java.awt.Dimension(156, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ANCIENNE VALEUR $");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 27));

        TEX.setBackground(new java.awt.Color(203, 203, 203));
        TEX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TEX.setText("00");
        TEX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TEX.setFocusable(false);
        TEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXActionPerformed(evt);
            }
        });
        jPanel2.add(TEX, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 5, 30, -1));

        jLabel3.setText("NOUVELLE VALEUR $");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 20));

        DAKH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DAKH.setText("00");
        DAKH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        DAKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DAKHMouseClicked(evt);
            }
        });
        DAKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAKHActionPerformed(evt);
            }
        });
        DAKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DAKHKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DAKHKeyTyped(evt);
            }
        });
        jPanel2.add(DAKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 30, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(TER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TER, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 64, 200, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void setSTF(String STF)
{
    this.STF=STF;
}
public String getSTF()
{
    return STF;
}

    private void TEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXActionPerformed

    private void DAKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAKHActionPerformed
int C=2;
    private void DAKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DAKHKeyTyped

        
        
        
        
        char STR=evt.getKeyChar();
        STR=Character.toUpperCase(STR);
        
        if(!Character.isDigit(STR) && STR !='F' && STR !='A' && STR !='B' && STR !='E'&& STR !='D' && STR !='C')
            evt.consume();
        if(evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)
        {
            if(C>0)
          C--;
          
        }
        else
        {
       
        if( C>=2)
        {
            evt.consume();
           
        }
        if(C<2)
         C++;
        }
        
        
    }//GEN-LAST:event_DAKHKeyTyped
public int GOT=0;
public void setGOT(int GOT)
{
    this.GOT=GOT;
}
public int getGOT()
{
    return GOT;
}
    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
    
        String B[]=STR.split("   ");
   B[1]=DAKH.getText();
    STR=B[0]+"   "+B[1];
  //  System.out.print(STR);
new Memory(STR);
     
             
         this.dispose();
   robo.keyPress(KeyEvent.VK_ENTER);
         robo.keyRelease(KeyEvent.VK_ENTER);
         robo.keyPress(KeyEvent.VK_ENTER);
         robo.keyRelease(KeyEvent.VK_ENTER);
   
    }//GEN-LAST:event_OKActionPerformed
public static int I;

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed

this.dispose();
    }//GEN-LAST:event_EXITActionPerformed

    private void DAKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DAKHMouseClicked
      
        
         if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 )
      {
                C=0;   

      }
         
    }//GEN-LAST:event_DAKHMouseClicked

    private void OKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OKKeyTyped

        
    }//GEN-LAST:event_OKKeyTyped

    private void DAKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DAKHKeyPressed
     if(evt.getKeyChar()== KeyEvent.VK_ENTER)
    
{
    
    
    
  String B[]=STR.split("   ");
   B[1]=DAKH.getText();
    STR=B[0]+"   "+B[1];
new Memory(STR);
     
             
         this.dispose();
         robo.keyPress(KeyEvent.VK_ENTER);
         robo.keyRelease(KeyEvent.VK_ENTER);
         robo.keyPress(KeyEvent.VK_ENTER);
         robo.keyRelease(KeyEvent.VK_ENTER);
    

}
          
  

    }//GEN-LAST:event_DAKHKeyPressed

     private void SETICOn() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ICONS//MOTO.png")));
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DAKH;
    private javax.swing.JButton EXIT;
    private static javax.swing.JButton OK;
    private javax.swing.JLabel TER;
    private javax.swing.JTextField TEX;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
